### PR TITLE
Fixing paste across browsers, adding mobile support, CTRL V for paste, and custom MOTD.

### PR DESCRIPTION
**Pull request by ColdHeat**
Adding Ctrl V for paste is a little controversial, but I haven't used verbatim for much. I'm using butterfly to give students shells and Ctrl V is more intuitive for them. 

Paste across browsers was broken and it should work in all browsers now thanks to [LuicdChart](https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/). 

Mobile support with font-awesome thanks to Zoosk. Don't have the article link though. 

Custom MOTD from the other pull request but with the appropriate fallbacks to the original MOTD.

### CODE REVIEW

**Comment by itheiss** [comment]
LGTM
:+1:

**Comment by sekka1** [comment]
This would be great!

**Comment by paradoxxxzero** [comment]
I'm sorry but I can't merge this PR. In your PR the motd is broken, the copy paste is broken here (linux machine), there's an external js file and finally a js file that redo what is already mostly done in coffee.
I'll hopefully look into better mobile/ios support later.

**Comment by ColdHeat** [comment]
Fair enough, what browser isn't working on Linux?

**Comment by paradoxxxzero** [comment]
Paste should be fixed now, can you give a try ?

**Comment by warpkwd** [comment]
I tried version 2.0.0. using firefox 37.
I could not copy/paste with CTRL+shift+c or CTRL+shift+v or CTRL+v
I want to paste by key.

**Comment by paradoxxxzero** [comment]
Yeah, firefox doesn't seem to handle ctrl+shift+c ctrl+shift+v at all, it cannot be manually triggered either  without a local configuration change.

As of now `Alt + z`, `Ctrl + c` and `Alt + z`, `Ctrl + v` is working for keyed copy paste, this is not ideal but at least it's native copy paste events and it isn't conflicting with terminals hotkeys.

**Comment by warpkwd** [comment]
Thanks Mounier
Firefox could paste with Alt +z, Ctrl +v.
Btw,  v2.0.0 works IE11.
But IE11 can not copy/paste in any way.
It can not use Alt+z.

**Pull request closed without merging**
