### PR TITLE
Fix up --uri-root-path so behaves as one would expect for this.

### PR DESCRIPTION
**Pull request by GrahamDumpleton**
This fixes ``--uri-root-path`` so that when used, everything provided by the site is below the path supplied by the ``--uri-root-path`` option. The code as it existed only did it for some resources and not all, meaning it wasn't actually useful.

The change addresses problems raised in https://github.com/paradoxxxzero/butterfly/issues/155

The way the changes have been done means it is now also more tolerant of whether or not leading and trailing slashes are provided for the argument. Thus following variations will all be normalised and work:

```
/suburl
/suburl/
suburl
suburl/
```

Do note that although this fixes the issue with ``--uri-root-path`` not working as one would expect, it seems to have surfaced a separate issue in how option parsing is done. What was observed was that the ``--uri-root-path``  option would be ignored if the ``butterfly.conf`` file didn't exist. So has been necessary to create the file before ever running it with this option. Need to still look separately into what is wrong with option parsing as likely affects other options as well in some way.

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
Placement of generation of conf file moved so as not to trigger code import until after options are parsed. This allows code when imported to change behaviour based on options.

**Comment by paradoxxxzero** [comment]
Wonderful! Thanks for the PR.

**Comment by GrahamDumpleton** [comment]
FYI. I have updated to try and use the 3.2.4 version you released with this but it doesn't actually work, where as my original branch with change does. Still trying to work out why. The error in Javascript console is:

```
WebSocket connection to 'wss://myhostname//user/default/terminal/ws/user/default/terminal/session/79cad5ac-d58f-4e50-9c83-412f2e74cc50' failed: Error during WebSocket handshake: Unexpected response code: 404
```

I suspect the generation of the repeating slash after hostname in the path is the problem because that isn't going to be normalised, so I need to look at whether you made any other changes which have introduced that.

**Comment by GrahamDumpleton** [comment]
One possibility is that because I was naughty and didn't actually generate the minified version in proper way, that it wasn't actually the same as the original, so if you regenerated the minified version, has brought in version which wasn't quite correct.

**Comment by paradoxxxzero** [comment]
Ah Indeed, the coffee is minified in the release process. Did you edit the
built files? In that case would you mind doing the same in the coffee
files? I'm afk for the weekend.



Le sam. 8 sept. 2018 à 14:40, Graham Dumpleton <notifications@github.com> a
écrit :

**Comment by GrahamDumpleton** [comment]
As per new issue I created (https://github.com/paradoxxxzero/butterfly/issues/178), that wasn't the issue. I had made change correctly in both. The problem was you reverted change when updating package version. :-)

**Comment by paradoxxxzero** [comment]
Yeah that's it, the main.js and main.css files are generated from the
coffees / sass files. You have to change them and then build the main
files. Sorry I missed that form your PR.

Le sam. 8 sept. 2018 à 14:58, Graham Dumpleton <notifications@github.com> a
écrit :

**Comment by GrahamDumpleton** [comment]
Okay, now I understand what you mean about coffee files. :-)

**Pull request merged**
