### PR TITLE
fix i-hereby-...-whatsoever option

### PR DESCRIPTION
**Pull request by warpkwd**
i-hereby-...-whatsoever revise to i_hereby_whatsoever

### CODE REVIEW

**Comment by warpkwd** [comment]
I found this issue using with --unsecure option.

**Comment by paradoxxxzero** [comment]
What's the issue?

**Comment by warpkwd** [comment]
[root]# ./butterfly.server.py --host=xxxxxxxx --unsecure  --login --port=59595
Traceback (most recent call last):
  File "./butterfly.server.py", line 144, in <module>
    if options.i_hereby_declare_i_dont_want_any_security_whatsoever:
  File "/usr/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/options.py", line 109, in __getattr__
    raise AttributeError("Unrecognized option %r" % name)
AttributeError: Unrecognized option 'i_hereby_declare_i_dont_want_any_security_whatsoever'

==
Thank you.

**Comment by paradoxxxzero** [comment]
Okay I get it now, it works with new tornado version but not with 4.1. Thanks for the PR

**Pull request merged**
